version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - devnet

  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - devnet

networks:
  devnet:
    driver: bridge

volumes:
  appdata:
    driver: local
